### ISSUE TITLE
Unexpected Server restart with /ms restart

### ISSUE THREAD

**Issue by QuickWrite** [Butzlabben/missilewars#1]
When an operator types in `/mw restart` or `/mw appendrestart` not only MissleWars restarts, but the whole Spigot server restarts as well.
Even though this is expected behaviour this is not optimal in every situation and/ or is not conveyed enough. This can be problematic with Spigot servers that have other gamemodes and the operators just want to restart MissleWars.

So I would recommend either an option in the `config.yml` or an extension to the command so that they look like this: `/mw restart <game|server>` or `/mw appendrestart <game|server>` and when no parameter is given the `game` is the default option so that nothing else is bothered.

**Comment by daniel-naegele** [comment]
Hi,

the `/mw appendrestart` command does exactly what it is supposed to do. This command can be helpful, if you changed some server settings, but don't want to interrupt the current game.

A restart in `/mw restart` can happen, if you have configured the `restart_after_fights` option in your config.yml to a non zero value and you reached the maximum of restarts.
If the issue still persists independently from this config value, please provider further information like version number, config and debug log outputs.

**Comment by QuickWrite** [comment]
> Hi,
> 
> the `/mw appendrestart` command does exactly what it is supposed to do. This command can be helpful, if you changed some server settings, but don't want to interrupt the current game.
> 
> A restart in `/mw restart` can happen, if you have configured the `restart_after_fights` option in your config.yml to a non zero value and you reached the maximum of restarts. If the issue still persists independently from this config value, please provider further information like version number, config and debug log outputs.

This was not a bug report, rather an info that the command should not restart the whole server as it makes no sense at all as there are already commands like this in the game: `/restart`.
I just wanted it to just restart the plugin by reloading the config and cleaning the objects from memory.

And when necessary there can be an additional value that allows the operator to restart the whole server with the MissleWars plugin.

**Comment by daniel-naegele** [comment]
` I just wanted it to just restart the plugin by reloading the config and cleaning the objects from memory.`
This is exactly what /mw restart does
