### ISSUE TITLE
receive missiles more often with the game progresses

### ISSUE THREAD

**Issue by Sayrix** [Butzlabben/missilewars#10]
Hey, can you make it so that the longer the game lasts, the more eggs you get, for example after 10 minutes of game, you get an egg every 10 seconds, after 20 minutes of game you get an egg every 5 seconds and so on

**Comment by RedstoneFuture** [comment]
Hi. Thanks for the idea. I will think about it. :)

**Comment by Sayrix** [comment]
Thank you very much!

**Comment by Sayrix** [comment]
Any news ?

**Comment by RedstoneFuture** [comment]
I'm done refactoring the previous game randomizer. I had to rework everything first until I can add new features.

**Comment by Sayrix** [comment]
ok good luck

**Comment by Sayrix** [comment]
Thanks ! (idk if it's integrated, if it's, you can close the issue)
