### ISSUE TITLE
Team color in tab

### ISSUE THREAD

**Issue by XXY233** [Butzlabben/missilewars#101]
**Is your feature request related to a problem? Please describe.**
Hello, I used this plugin a few years ago, when the color of the player name in the tab was related to the team. But does the latest version not have this function, and the names are all white?
![image](https://github.com/daniel-naegele/missilewars/assets/46647646/bc143551-3422-40e5-821b-cafc61305b8a)

**Describe the solution you'd like**
Player name in tab with team color

**Comment by RedstoneFuture** [comment]
Hi, the tablist color is realized differently on each server.

Many servers have a Bungee/Bukkit plugin for the Tablist, which allows you to use the [MissileWars - PlaceholderAPI placeholders](https://github.com/daniel-naegele/missilewars/wiki/Placeholders-for-PlaceholderAPI) here. The color can also come from the permission system or be overridden by other plugins.

I like to take a look at what additional solutions make sense for which setup and what are the solutions of other plugins. But there is certainly no solution here that will always work for all servers.

Thanks for the report.

**Comment by RedstoneFuture** [comment]
I have added new [PAPI placeholders](https://github.com/RedstoneFuture/missilewars/wiki/Placeholders-for-PlaceholderAPI) that any tab-list plugin with PAPI support can use. You can find an example setup with a known tab-list plugin [in this new wiki article](https://github.com/RedstoneFuture/missilewars/wiki/Custom-Tab-List).

I hope this helps.
