### ISSUE TITLE
stats don't work

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#120]
**Describe the bug**
statistics command not working

**To Reproduce**

Type the command /mw stats players
Watch the console

**Expected behavior**

The command will be functional

**Screenshots**

![image](https://github.com/daniel-naegele/missilewars/assets/29830635/d8e79195-f842-46d2-be93-d24035ca3c05)

**Server (please complete the following information):**

- OS: [e.g. Debian, Windows]
- Minecraft version [e.g. 1.12, 1.16, 1.17] purpur 1.20.2
- Java version [e.g. 11, 17]

**Additional context**

Error: https://pastebin.com/SPXdKeXp

**Comment by daniel-naegele** [comment]
Where there any other errors before this one? Could you try to replicate it and send the whole log?
Could you test with the new version what happens?

**Comment by 100petr** [comment]
sorry for the late reply, I didn't have time earlier
I try the new version and on 1.20.4 and it works. Thanks.
