### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#124]
**Describe the bug**
Hello,
I tried to setup the plugin on my server exactly as per the tutorial on your Wiki.

I'm using FAWE, minecraft 1.20.4, plugin list:

Once I complete the setup and create a sign on the default lobby, I click on the sign and it doesn't throw me anywhere. The game won't start and won't even start, I don't see anything in the inventory. To the other player, switching teams and other items from the plugin appear in the inventory, but the game doesn't start and nothing further happens.

I'm using the default map and default lobby, with the lobby set to a world called "arcade".

 Paper Plugins: (1):
- SignedVelocity
Bukkit Plugins: (49):
- AntiPopup, ArmorStandTools, *asCMD, BeastTokens, CancelChat, Citizens, CustomAdvancements, CyberLevels, DecentHolograms, DeluxeMenus, DiscordSRV, Essentials, ExcellentCrates, FastAsyncWorldEdit, goBrush, goPaint, Guilds, HideAndSeek, *HostifyMonitor, ItemsAdder, LibsDisguises, LiteBans, LoneLibs, LuckPerms, MineMarket, MissileWars, Multiverse-Core, MyCommand, NexEngine, NoPlugins. Panilla, PAPIProxyBridge, PlaceholderAPI, Plan, PlugManX, ProtocolLib, QualityArmory, Skywars, spark, SurvivalGames, SyncCommands, TAB, Vault, ViaBackwards, ViaVersion, VoidGen, VoxelSniper, Vulcan, WorldGuard

**To Reproduce**
Run the plugin setup with custom world for lobby.

**Expected behavior**
It should let me play the game.

**Screenshots**

**Server (please complete the following information):**

- OS: Debian
- Minecraft version 1.20.4
- Java version 17
- Version 4.6.0

**Additional context**
Full log:

https://paste.gg/p/anonymous/03e37cafa6104930811bcb6889b09e34

**Comment by RedstoneFuture** [comment]
Hi. It looks like you are trying to change teams before you enter the lobby area.

```
[16:53:07] [Server thread/INFO]: [MW] Info | pjindras joint the MW game lobby0
[16:54:12] [Server thread/INFO]: [MW] Info | pjindras left the MW game lobby0
[...]
[16:54:12] [Server thread/INFO]: [MW] Boot | Reloaded lobby "lobby0" (lobby0.yml) [DONE]
[16:54:12] [Server thread/INFO]: [MW] Boot | Loading lobby "lobby0".           <--- now the lobby is ready
[...]
[16:54:26] [Server thread/ERROR]: [MissileWars] [ACF] Exception in command: mw change 1
```

Enter the Lobby Arena and then you will be part of the game. If no one is in a lobby, there is no active game and therefore no team.

**Note:** You can change your "lobby area" and the lobby "spawnpoint" with the `/mw setup` command. (Unfortunately, the wiki is not currently complete.)

Also make sure that the sign displays the correct values when you click on it - i.e. that the status of the game is displayed correctly. If this is not the case, something may have gone wrong before you entered.

**Comment by pjindras** [comment]
I found the problem, the player was outside of lobby area in the same world, but different height. I solved that, thank you.
