### ISSUE TITLE
Question: New release

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#136]
Hi, please when you plan an update / new release / pre-release? :D 
Only if its possible to give us a time frame.

Thank you

**Comment by RedstoneFuture** [comment]
Hello, I would like to release a new full version of this plugin in September.

I have greatly improved and customized the plugin in some areas over the last few months and wanted to have some stability to be able to support the next release.

**Comment by pjindras** [comment]
> Hello, I would like to release a new full version of this plugin in September.
> 
> I have greatly improved and customized the plugin in some areas over the last few months and wanted to have some stability to be able to support the next release.

do you have some test build please? I can test it for you, if you need

**Comment by pjindras** [comment]
@RedstoneFuture please do you have some progress? unfortunately we found some bugs etc. but I want to wait for a new release before posting it all because it might be fixed there already

**Comment by RedstoneFuture** [comment]
As I'm currently finishing a few things, hopefully next week.

**Comment by RedstoneFuture** [comment]
The release will follow soon. I'll announce it in Discord.
