### ISSUE TITLE
Team selection bugged

### ISSUE THREAD

**Issue by pjindras** [Butzlabben/missilewars#137]
**Describe the bug**
We were after one game again at lobby and one player changed team from red to green.
There were 3 red and 1 green players.

Noone could change team to green-> it was posting message, that it wouldnt be balanced, but it wasnt balaced -> it was 3 on 1.

Game cannot start, but players cannot change their team to balance the teams.

**Server (please complete the following information):**

- OS: Debian
- Minecraft version 1.20.4
- Java version 21
- Version: 4.6.0

**Comment by RedstoneFuture** [comment]
The team size validation has been revised again in the latest versions. Please test the latest version when it is released. Thank you.
