### ISSUE TITLE
Items are disapearing

### ISSUE THREAD

**Issue by AlloryDante** [Butzlabben/missilewars#56]
Hello, Items are disapearing after you die.If keepinventory is set true, each time you die, I receive a bow.

Solution: Try to clear inventory and regive items back to player on death.

Tested on 1.19.2

**Comment by RedstoneFuture** [comment]
Which MW version are you using?

**Comment by AlloryDante** [comment]
> Which MW version are you using?

v4.3.1

Also I use this plugins  AdvancedNMotd, AnimatedScoreboard, AuthMe, DecentHolograms, Essentials, EssentialsChat, EssentialsSpawn, LightChatBubbles*, MissileWars, PacketListenerApi, PermissionsEx*, PlaceholderAPI, ProtocolLib, Spartan, Vault, WorldEdit, WorldGuard

**Comment by RedstoneFuture** [comment]
When the gamerule `keepInventory` is disabled, the player loses his items with death. This is also wanted so far.

If the gamerule `keepInventory` is activated, you still get a bow when you rejoin. I will fix that! (https://github.com/RedstoneFuture/missilewars/blob/3b9916e06be047d81b4470920a42d0a415e4b5dd/missilewars-plugin/src/main/java/de/butzlabben/missilewars/listener/game/GameListener.java#L180)

Thank you for the report.

**Comment by AlloryDante** [comment]
Yes, it would be better to have a setting that ovverides keepinventory.Somethink like

keepItems:true -> Player wont loose items on death
                  false -> Player will keep the items on death
For example I would like to have all my players keep their items so the game becomes more intese.

**Comment by RedstoneFuture** [comment]
Using vanilla gamerules, would be the same as lobby/arena settings: it is not more complicated for the administrator to use them.

Otherwise, we would have to create a setting for all other world gamerules to "replace" them. (doWeatherCycle, doDaylightCycle, doMobSpawning, ...)

**Comment by AlloryDante** [comment]
Ok.I will have to install a per world permission plugin then to allow keepinventory.Anyway, thank you for mentaining this great plugin.Its super fun.

**Comment by RedstoneFuture** [comment]
You only have to set the gamerule once in the MissileWars World Template.

e.g. `\MissileWars\arenas\default_map\level.dat`

**Comment by RedstoneFuture** [comment]
@cezarlacatus Now, the arena config option `keep_inventory` will change the vanilla gamerule `keepInventory` too.
