### ISSUE TITLE
GUI reworking

### ISSUE THREAD

**Issue by RedstoneFuture** [Butzlabben/missilewars#60]
The main reason for the new GUI concept is the requirement for the possibility to enter the "spectater" group in the lobby already.

It is also planned to be able to select the group (A, B, Specate) via Menu 2 when entering a game that is already running. The new player will be in Godmode for a short time after entering the arena.

---

**Main menu: Hotbar**
![grafik](https://user-images.githubusercontent.com/4140635/210408323-717b1942-edca-44a5-9f29-bd0a2cf59fa5.png)
- link for team menu
- link for world voting menu
- info about the area statics [new]

**Team selection: Chest-Menu**
![grafik](https://user-images.githubusercontent.com/4140635/210406838-aaf1993e-d343-4002-ab78-923025698068.png)
- team a
- spectate [new]
- team b

**Comment by daniel-naegele** [comment]
What dooes the info about the area statics display? Which menu gets opened?  Are there any plans to enable maximum UI configurability, such as with WorldSystem if known?

**Comment by RedstoneFuture** [comment]
> What dooes the info about the area statics display? Which menu gets opened? Are there any plans to enable maximum UI configurability, such as with WorldSystem if known?

The statistics / info are listed with the item with an item lore. That should be enough.

I have not yet dealt with the MW's statistics system. But statistics / info, like:
- the name of the arena, the name of the lobby
- how often you played there
- how often you have won there
- Game time
- [optional] the size of the arena (length, width), ...
- [optional] number of missiles
- [optional] Spectator possible?
- [optional] Entering during the game possible?

It could be fully configurable with variables.

I do not think that a "maximum UI configurability" is necessary.

**Comment by daniel-naegele** [comment]
What happens when voting/statistics are disabled? What will be the layout then? What about the item names/description? Will they have special colors and/or be configurable via messages.yml?

**Comment by RedstoneFuture** [comment]
I think it would be good if the admin can configure the item title and the full item lore of the "stats/info" item. So if the statistics are disabled, he can also delete the statistic lines.

If the voting of the world is disabled, we could make the item invisible. Or we could show a black/white version of the globe item.

**Comment by daniel-naegele** [comment]
We need for all possible combination for the UI to adapt to that, so that the hotbar stays symmetric. In addition I would maybe use another item for the team selection, as the green helmet is a bit unambigous in regards of what it actually does. I would suggest an armor stand.

Besides that, I totally approve of the suggested changes
