### ISSUE TITLE
Plugin is not Loaded

### ISSUE THREAD

**Issue by AlmarBlock** [Butzlabben/missilewars#63]
**Describe the bug**
When I run the latest version of the plugin on a 1.14.4 server, the plugin doesn't load.

**To Reproduce**
1. I starten the MC Server whis the Version 1.14.4
2. Than I used the Command "/plugins"
3. And the response was that all plugins (World edit and ViaVerion) were active normally, but Missile Wars was red and inactive.

**Expected behavior**
That The Plugin Missle Wars is green and active

**Screenshots**
![image](https://user-images.githubusercontent.com/98546933/215294597-8669764b-9ff4-4d1a-ab09-46bd8097d70a.png)

**Server (please complete the following information):**
 - OS: Debian 11
 - Minecraft version: 1.14.4
 - Java version: 11
 - Version: 4.3.1

**Additional context**
Sorry for the English. (I´m German)

**Comment by RedstoneFuture** [comment]
The plugin should work in 1.14.4 basically. I need more info.
Can you please look for error messages/warnings by MissileWars in the server log and post them (e.g. via [Pastebin](https://pastebin.com)), please?

**Comment by AlmarBlock** [comment]
https://pastebin.com/XPX2Rgv7 Here is the console-log. (https://github.com/Butzlabben/missilewars/releases/tag/v4.3.1 is the Download that i used.)

**Comment by RedstoneFuture** [comment]
Unfortunately, since releases are not automatic at this time, the current release of Oct 2022 is a little outdated. A suggestion would be to test the latest version when a new release is out.

Alternatively, you could check the MOTD configuration.

**Comment by RedstoneFuture** [comment]
Hi. Can you please test it with the [latest version](https://github.com/Butzlabben/missilewars/releases) (4.4.0)?

**Comment by AlmarBlock** [comment]
I got it to show up green, but I didn't got et to work. Because the documentation isn't really complete and the video on Spigot.org is for an old version.

**Comment by RedstoneFuture** [comment]
All you need for the first startup is this:
https://github.com/Butzlabben/missilewars/wiki/Getting-Started
