### ISSUE TITLE
Shield will not be loaded

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#68]
**Describe the bug**
The schematic of the shield is misplaced. It should be in missiles, but it isn't. When I move it (even with the server turned off) it still won't stay there.

**To Reproduce**

Try moving the shield to the correct folder, it won't stay there.

**Expected behavior**

The shield will be in the correct folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/29830635/230894396-84bac2d7-212f-4d46-9e96-e47626b3e149.png)

**Server (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Minecraft version [e.g. 1.12, 1.16, 1.17] purpur 1.19.3
 - Java version [e.g. 11, 17] 

**Additional context**

**Comment by RedstoneFuture** [comment]
1. "Furthermore, the schematic of the shield is misplaced. It should be in missiles, but it isn't."
No, it is not a missile. `/plugins/MissileWars/shield.schematic` is currently correct.

**Comment by 100petr** [comment]
In that case it doesn't work https://pastebin.com/LHExueYP

**Comment by RedstoneFuture** [comment]
Please do not include 2 issue reports in one Github issue.

**Comment by 100petr** [comment]
Ok, I'll split it up.

**Comment by 100petr** [comment]
Should be. Otherwise, I read the error more carefully now and see that the shield should be in the shields folder. I will try to create it now, how it will behave

**Comment by 100petr** [comment]
so yes, it already works when creating the shields folder, but it's still generated in the plugin folder.

**Comment by RedstoneFuture** [comment]
Which version do you use?

**Comment by 100petr** [comment]
4.4.0
