### ISSUE TITLE
Player Data does not load from file

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#70]
**Describe the bug**

We found that the plugin deletes items that were in the inventory before connecting to the game

**To Reproduce**
1. Take some items
2. Join the game
3. Leave the game

**Expected behavior**

Items in inventory will remain. Alternatively, an empty inventory will be required to join the game.

**Screenshots**

https://user-images.githubusercontent.com/29830635/230905229-39cef16c-7647-4d58-bfcb-690c846f9580.mp4

**Server (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Minecraft version [e.g. 1.12, 1.16, 1.17] purpur 1.19.3
 - Java version [e.g. 11, 17]

**Additional context**

I'm sorry I found your plugin and now I'm overwhelming you :D but I promise that when the things I wrote are resolved, we'll happily buy the plugin

**Comment by RedstoneFuture** [comment]
Dev-Note: A part of this (only for data loading from file): https://github.com/RedstoneFuture/missilewars/blob/2e78c712316fc5e26344f8385d349cdf296cf0c1/missilewars-plugin/src/main/java/de/butzlabben/missilewars/player/PlayerData.java#L67
