### ISSUE TITLE
Team change - wrong syntax check

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#71]
**Describe the bug**

I can't change the team - it says too many arguments (see screen). 

**To Reproduce**

Try to change the team - error

**Expected behavior**

Changing the team will work

**Screenshots**

![image](https://user-images.githubusercontent.com/29830635/230893940-1620db91-2923-4cc5-aa75-307a3311952b.png)

**Server (please complete the following information):**
 - OS: [e.g. Debian, Windows]
 - Minecraft version [e.g. 1.12, 1.16, 1.17] purpur 1.19.3
 - Java version [e.g. 11, 17]

**Additional context**

**Comment by RedstoneFuture** [comment]
I can confirm this. I'll take a look at it again.

**Comment by daniel-naegele** [comment]
Should be fixed in the newest release  `v4.5.0`
