### ISSUE TITLE
custom chat in the game

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#74]
**Is your feature request related to a problem? Please describe.**

Not quite. But other players can be disturbed by the fact that they read the messages of those who are currently playing missilewars and are not aware of what is happening

**Describe the solution you'd like**

I would imagine a separate chat, so if I'm in the game, my chat messages would only be seen by players who are also in the game.

**Describe alternatives you've considered**

**Additional context**

and one offtopic thing, is it better for you to support via the donate button or by buying a plugin?

**Comment by daniel-naegele** [comment]
This is a good idea.
Although we also need a discussion on how to exactly implement this feature, there are several open questions like:
- How to format the messages? 
  - Is there a way to leave the formatting to the server owner with other plugins and only intercept not wanted messages? 
  - Make the formatting maybe configurable?
- Do we have a teams only chat?
  - Can for example the both teams chat accessed by a prefix like `@a`
  - Can players still write to the global chat with @g?
- How to make this as open, configurable and customizable as possible

Feel free to leave suggestions, ideas, proposals etc.

**Comment by RedstoneFuture** [comment]
There are not so many bungee chat plugins that actually run on the bungee. But if you use one of them, the chat will be intercepted by the bungee before anyway. For these servers the feature is not usable then.

**Comment by RedstoneFuture** [comment]
`and one offtopic thing, is it better for you to support via the donate button or by buying a plugin?`

If it still costs something at [Spigot](https://www.spigotmc.org/resources/authors/butzlabben.455493/), you can buy it or use Butzlabben's donation link ([for PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=naegele_daniel%40web.de&currency_code=EUR&source=url)). I think, it does not matter. :)

**Comment by daniel-naegele** [comment]
If you buy it, PayPal deducts a small fee, but you can request a refund if wanted.

**Comment by 100petr** [comment]
For example, paintball has its own chat. It has its own in-game chat format. Which may bother some and not others.  https://github.com/Ajneb97/PaintballBattle
The possibility of using the global chat for example with some characters is not bad, I don't know how feasible it is

**Comment by 100petr** [comment]
I thought the missilewars chat would annoy others who don't play it. no one has complained about it in about a month, so probably unnecessary.
