### ISSUE TITLE
automatic connection to missilewars

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#75]
**Is your feature request related to a problem? Please describe.**

Now if the player approaches the lobby (or whatever it is) it automatically pulls them into the game.

**Describe the solution you'd like**

I would imagine the possibility of turning off this automatic connection to the game (feel free to put it in the config as an option to turn it on/off), so that the player has to connect manually with a sign/command.

**Describe alternatives you've considered**

**Additional context**

**Comment by daniel-naegele** [comment]
This happens, if the spawn point of the player/server is in a lobby. Then they will be added in the game.

If not, the player must enter manually/use a sign/use a teleport command whatsoever. So this feature is already kinda implemented.

**Comment by 100petr** [comment]
I meant it so that the automatic connection could be turned off. perhaps so that one lobby can be used for multiple games. It will take the player who approaches to the Spawn lobby to about 10 blocks

**Comment by RedstoneFuture** [comment]
> I meant it so that the automatic connection could be turned off. perhaps so that one lobby can be used for multiple games. It will take the player who approaches to the Spawn lobby to about 10 blocks

They can use the signs in their server lobby and send the players from there to the MW lobby. The MW lobby is necessary as a waiting lobby for the MissileWars game and equips the players, activates the map vote etc.
The "AfterGameSpawn" and the lobby spawn can be set quite freely with the setup command.

**Comment by 100petr** [comment]
Ok, we'll try to look into it. It is true that we did not test the specific settings, because we are still playing with the plugin on the test server. I just saw with my eyes that there is such a setting
