### ISSUE TITLE
Refactoring of Games.java

### ISSUE THREAD

**Issue by RedstoneFuture** [Butzlabben/missilewars#80]
The class `Games.java` is the central object for a game. However, some methods and fields can be outsourced to manager classes to keep the Games class a bit more manageable. The following is a suggestion for outsourcing:

**Games.java**
- NEW: _method_ EquipmentManager()
- NEW: _method_ TaskManager()
- DELETE: _method_ getScoreboard() -> Using of ScoreboardManager

**Moving from `Game.java` to `Lobby.java`**
- _method_ teleportToLobbySpawn()
- _method_ teleportToAfterGameSpawn()

**Moving from `Game.java` to `Arena.java`**
- _method_ teleportToArenaSpectatorSpawn()

**Moving from `Game.java` to `EquipmentManager.java`**
- _field_ ItemStack customBow (+ Getter)
- _field_ ItemStack customPickaxe (+ Getter)
- _field_ MissileGameEquipment missileEquipment (+ Getter)
- _field_ SpecialGameEquipment specialEquipment (+ Getter)
- _method_ createGameItems()
- _method_ sendGameItems()

**Moving from `Game.java` to `TaskManager.java`**
- _field_ Timer timer (+ Getter)
- _field_ BukkitTask bt (+ Getter)

**Comment by daniel-naegele** [comment]
This is definitely a good idea.
I would split in this into smaller PRs, with the addition of the EquipmentManager, TaskManager each.

**Comment by RedstoneFuture** [comment]
I am not sure if moving the `teleportTo` methods is useful at the moment. I'm thinking about moving some player based methods (`removePlayer`, `broadcast`, `startForPlayer`, `setPlayerAttributes`, the teleport methods, ...) to a separate manager - but not yet.
