### ISSUE TITLE
empty inventory required to connect

### ISSUE THREAD

**Issue by 100petr** [Butzlabben/missilewars#84]
**Is your feature request related to a problem? Please describe.**

Could be. This time my idea is to set the player to have an empty inventory to join the game. You fixed the inventory save last time, but I'd still prefer them to have nothing in the inventory (you never know what can go wrong).

**Describe the solution you'd like**

I would imagine a setting so that you can only join the game with an empty inventory. For example require-empty-inv: true/false

**Describe alternatives you've considered**

Alternatively, it might not be in the global setting, but would be set for each arena separately

**Additional context**

**Comment by RedstoneFuture** [comment]
I don't think the setting is useful. You can see in the code when and how the items are removed. We delete the items before the game-lobby join and assign the team switch items if necessary. After the teleport to the game-area we assign the standard items. If there are any problems in this process, the game is not usable - so please report bugs or check plugin compatibility.

The proposed setting makes little sense and is not a clean solution to any problem. Currently, the item clear process seems to work fine.

**Comment by 100petr** [comment]
Yes, I haven't encountered this problem with your plugin yet after fixing inventory save (I can't remember now if I encountered it with another plugin, but the plugins I already use that have this feature, I have it enabled in them). But I leave it up to you how you deal with it.

**Comment by RedstoneFuture** [comment]
Basically, from an admin point of view, I can understand this security aspect. But even an "Inventory-is-clear" check cannot theoretically give 100% security if there are already any compatibility problems or problems with the inventory synchronization. The safest way here is to move the game lobby to another world with a separate inventory.
