### ISSUE TITLE
Events are not executed

### ISSUE THREAD

**Issue by Gamer-Bjoern** [Butzlabben/missilewars#95]
If I want to use the events GameStartEvent and GameStopEvent, they are not executed.
My Code: 

class MissleWarsListener : Listener {
    @EventHandler
    fun onStart(event: GameStartEvent) {
        
    }

    @EventHandler
    fun onStop(event: GameStopEvent) {
        
    }
}

**Comment by daniel-naegele** [comment]
I was not able to reproduce the mentioned bug, could you provide a complete reproducible server .zip with all files, plugins needed to properly reproduce this?
Did you perhaps forgot to register the Listener class via `Bukkit.getPluginManager().registerEvents()`?

**Comment by Gamer-Bjoern** [comment]
No I have the JoinListener in the same Class and the JoinListener works

**Comment by daniel-naegele** [comment]
Have you tested it with both `GameStartEvent` and `GameStopEvent`?
Can you specify which versions of MissileWars, Minecraft, Java and OS do you use?
Also could you send me the reproducible example?

**Comment by RedstoneFuture** [comment]
> Have you tested it with both `GameStartEvent` and `GameStopEvent`? Can you specify which versions of MissileWars, Minecraft, Java and OS do you use? Also could you send me the reproducible example?

@Gamer-Bjoern Can you please post the information you requested?
